### ISSUE TITLE
Akka serialization configuration?

### ISSUE THREAD

**Issue by agemooij** [krasserm/akka-analytics#2]
This project looks very interesting but I'm wondering where and how to configure deserialization of the persisted events. The examples all seem to assume that all events have been serialized with Java Serielization but in real life that doesn't (or shouldn't) happen very much. 

We use a custom serializer to persist `PersistentRepr` and its payloads while some people use the default serializer for `PersistentRepr` but with a custom serializer for the payloads. In both cases I'd like to know how to configure the analytics code to use the correct (de)serializers.

**Comment by krasserm** [comment]
Yes, the examples actually use Java serialization. Here's a description how you can customize (de)serialization. For batch-processing from Cassandra
- you can customize `PersistentRepr` payload (de)serialization as described in the [akka-persistence docs](http://doc.akka.io/docs/akka/2.3.9/scala/persistence.html#custom-serialization). Default is Java serialization.
- The `PersistentRepr` wrapper by default is serialized with protobuf by akka-persistence. You can customize that by overriding the serializer settings in the [akka-persistence config](http://doc.akka.io/docs/akka/2.3.9/general/configuration.html#config-akka-persistence).

The configuration is the same for plain akka-persistence applications as well as akka-analytics applications. For stream-processing from Kafka, the situation is currently a bit more involved (which will be enhanced in later versions, as described below). The [akka-persistence-kafka](https://github.com/krasserm/akka-persistence-kafka) plugin stores events twofold:
- once internally, for `PersistentActor`s to write and read messages. Here (de)serialization can be customized as described for Cassandra above. However, this is currently not where akka-analytics reads messages from.
- akka-analytics reads messages from [separate user-defined topics](https://github.com/krasserm/akka-persistence-kafka#user-defined-topics). The akka-persistence-kafka plugin writes messages to user-defined topics in addition to journal topics.

For writing to and reading from user-defined topics, akka-persistence-kafka by default uses [DefaultEventEncoder](https://github.com/krasserm/akka-persistence-kafka/blob/v-0.3.4/src/main/scala/akka/persistence/kafka/Event.scala#L40) and [DefaultEventDecoder](https://github.com/krasserm/akka-persistence-kafka/blob/v-0.3.4/src/main/scala/akka/persistence/kafka/Event.scala#L50), respectively. 
- On the producer side, you can provide your own encoder by setting the `kafka-journal.event.producer.serializer.class` configuration key (see akka-persistence-kafka docs for details). 
- On the consumer side (i.e akka-analytics), you specify a corresponding decoder as type parameter in [eventStreamWithDecoder](https://github.com/krasserm/akka-analytics/blob/master/akka-analytics-kafka/src/main/scala/akka/analytics/kafka/package.scala#L19) which I [just committed](https://github.com/krasserm/akka-analytics/commit/a7853042d7c5ac959b57afafee94b304b8567b37). So far, this was hard-coded to be a `DefaultEventDecoder`.

With these configuration options you should be able to fully customize (de)serialization when reading from both Cassandra and Kafka.

Upcoming implementations of `DefaultEventEncoder` and `DefaultEventDecoder` will [delegate to Akka serialization by default](https://github.com/krasserm/akka-analytics/issues/3). Then you just need to configure a single payload de(serializer) which will be used for both journal and user-defined topics.

Hope this clarifies things a bit. Thanks for having brought this topic up. Of course, pull requests are always welcome :)

Cheers,
Martin

**Comment by agemooij** [comment]
Thanks Martin, that clarifies things.

Hopefully I'll have some time to play with this library soon and I'll let you know what we run into.

Keep up the (ridiculously high output of) good work ;)
Age

**Comment by krasserm** [comment]
@agemooij I just released 0.3 with full [custom serializer support](https://github.com/krasserm/akka-analytics/blob/master/README.md#custom-serialization). Serializers can now be configured in the same way as in akka-persistence.

**Comment by agemooij** [comment]
Nice! Thanks!
