### ISSUE TITLE
Problems with manifest serializer.

### ISSUE THREAD

**Issue by hsperr** [krasserm/akka-analytics#4]
Hey,

First for all thanks for that awesome project, 
I am using akka persistence to serialize my objects into cassandra and wanted to use your library to do analytics on that data. Serializing and Deserializing in my other akka project works but with spark analytics there is a problem that he cannot find the correct serializer for my manifest.
Connecting to cassandra with spark and just reading the columns using the datastax driver works.

I am using:
- akka-persistence 2.4
- akka-analytics-cassandra 0.3
- spark-core 1.4.0

First problem I encountered was that 

```
https://github.com/krasserm/akka-analytics/blob/master/akka-analytics-cassandra/src/main/scala/akka/analytics/cassandra/JournalSparkContext.scala#L55
```

Akka persistance does not seem to create a column called "processor_id" for me, mine is called "persistence_id" so the select query fails, after solving that on my local all my entries are Ignored though because my serialiser cannot be loaded.

My Akka config looks something like this:

```
akka {
  actor {
    serializers {
      my-serializer = "com.mypackage.MySerializer"
    }

    serialization-bindings {
      "com.mypackage.MySerializable" = my-serializer
    }
  }
}
```

And my Serialiser like this:

```
class MySerializer extends SerializerWithStringManifest {

  final val V1Manifest = "MySerializer.v1"

  def identifier: Int = 532134017
```

I put a println statement in the failure part of the `deserialize` method of your JournalEntryTypeConverter to see the error (https://github.com/krasserm/akka-analytics/blob/master/akka-analytics-cassandra/src/main/scala/akka/analytics/cassandra/JournalSparkContext.scala#L33):

```
java.lang.ClassNotFoundException: MySerializer.v1
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at akka.actor.ReflectiveDynamicAccess$$anonfun$getClassFor$1.apply(DynamicAccess.scala:67)
    at akka.actor.ReflectiveDynamicAccess$$anonfun$getClassFor$1.apply(DynamicAccess.scala:66)
    at scala.util.Try$.apply(Try.scala:192)
    at akka.actor.ReflectiveDynamicAccess.getClassFor(DynamicAccess.scala:66)
    at akka.persistence.serialization.MessageSerializer.akka$persistence$serialization$MessageSerializer$$payload(MessageSerializer.scala:207)
    at akka.persistence.serialization.MessageSerializer.akka$persistence$serialization$MessageSerializer$$persistent(MessageSerializer.scala:193)
    at akka.persistence.serialization.MessageSerializer.fromBinary(MessageSerializer.scala:70)
    at akka.persistence.serialization.MessageSerializer.fromBinary(MessageSerializer.scala:26)
    at akka.serialization.Serializer$class.fromBinary(Serializer.scala:65)
    at akka.persistence.serialization.MessageSerializer.fromBinary(MessageSerializer.scala:26)
    at JournalEntryTypeConverter.deserialize(MyAkkaPersistance.scala:31)
```

Do you have any advice on this? I debugged a bit in the `deserialize` method of the serial object and found that it first calls `serializeFor(classOf[PersietentRepr])` and then `fromBinary(bytes, classOf[PersistentRepr])` which results in the crash mentioned above.

Thanks a lot for any advice,

Best,
Henning

**Comment by krasserm** [comment]
Hi Henning, have you set up your custom serializer as described in https://github.com/krasserm/akka-analytics#custom-serialization ?

Cheers,
Martin

**Comment by hsperr** [comment]
Hey,

thanks for your answer and sorry for the late reply. I now made sure that I can serialize and deserialize my events with akka-persistence, the above mentioned error with akka-analytics remains though.

Have you ever tried using akka-analytics with a custom serializer?

Best,
Henning

**Comment by krasserm** [comment]
> Have you ever tried using akka-analytics with a custom serializer?

Did you see the linked integration tests at the bottom of https://github.com/krasserm/akka-analytics#custom-serialization?

**Comment by hsperr** [comment]
Hey,
sorry for the late reply,
A colleague of mine figured it out, well, at least he just set the same project up and it works. Sadly I have no idea what went wrong.

The problem that persisted though was

```
Akka persistance does not seem to create a column called "processor_id" for me, mine is called "persistence_id" so the select query fails, after solving that on my local all my entries are Ignored though because my serialiser cannot be loaded.
```

If you can confirm that I can PR the change if you want.
The change would be here:

```
https://github.com/krasserm/akka-analytics/blob/master/akka-analytics-cassandra/src/main/scala/akka/analytics/cassandra/JournalSparkContext.scala#L55
```

I will also close the Issue if thats fine.

**Comment by krasserm** [comment]
In addition to the change you proposed, the Akka dependencies must also be upgraded from 2.3.x to 2.4.x. Other dependencies must be upgraded as well. The akka-persistence-kafka project still depends on Akka 2.3 but should also work with Akka 2.4 I think. Are you interested in making these upgrades and creating a PR?

**Comment by hsperr** [comment]
Hey, 

sorry again for the delay, sure, give me some time I will give it a look!

**Comment by hsperr** [comment]
Hey its me again, I am sorry I do not find time to work on this now, but since my problem is resolved I will close this Issue.
